### ISSUE TITLE
Fork (more or less)

### ISSUE THREAD

**Issue by kcraam** [kailashyogeshwar85/docker-rabbimq-cluster#1]
Hi, I was looking how to start a RabbitMQ mini-cluster and found your project! It's awesome.
I used as base to write a couple of Ansible recipes that do more or less the same.

Take look if you like:

https://gitlab.com/SensSolutions/rabbitmq-cluster

Kind regards

Marck

**Comment by kailashyogeshwar85** [comment]
Thanks! Saw your project and it looks promising. :+1:
