### ISSUE TITLE
You should be giving credit.

### ISSUE THREAD

**Issue by jdtempleton** [kailashyogeshwar85/docker-rabbimq-cluster#2]
I was searching the internet for how to run a RabbitMQ cluster using Docker and found your medium post about it. After reading it, I realized your post and method to implementing it was a direct copy of another person's work. You should have really forked the original repository, given credit to the original person, and made any changes you wanted to make to your fork. You could have even contributed to the original person's repository after making the changes. 

[Medium Post](https://kailashyogeshwar.medium.com/rabbitmq-cluster-using-docker-compose-7397ea378d73)
[Original Implementation](https://github.com/bijukunjummen/docker-rabbitmq-cluster)

**Comment by kailashyogeshwar85** [comment]
Added @BashfulBandit
